[package]
name = "bili-dm"
version = "0.3.0"
description = "A local-first desktop media player"
edition = "2021"
publish = false

[lib]
name = "bili_dm_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
url = "2"
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "net", "io-util", "signal"] }
tokio-util = { version = "0.7", features = ["io", "rt"] }
librqbit = { version = "=9.0.1", default-features = false, features = ["rust-tls", "disable-upload"] }
axum = "0.8"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
tauri-plugin-dialog = "2"
rusqlite = { version = "0.40", features = ["bundled"] }
libloading = "0.8"
raw-window-handle = "0.6"
futures-util = "0.3"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "gzip", "deflate", "system-proxy"] }
prost = "0.14"
md5 = "0.8"
qrcode = { version = "0.14", default-features = false }
rustfft = "6"
regex = "1"
png = "0.18"
base64 = "0.22"


[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
